version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: doctor-diary-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=doctor-diary
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

volumes:
  .postgres-data: